### ISSUE TITLE
OS indpendet paths for simple step function

### ISSUE THREAD

**Issue by HauHe** [KTH-dESA/OSeMOSYS_step#22]
Currently the paths used in the simple step function use unix format. The scripts will therefore not run on Windows.

**Comment by trevorb1** [comment]
I think maybe this one can be closed now to, @HauHe? On the develop branch, all paths are handeled through the [pathlib ](https://docs.python.org/3/library/pathlib.html) library now!

**Comment by HauHe** [comment]
Good catch! thanks
