### ISSUE TITLE
Limits clashing with solver tolerance

### ISSUE THREAD

**Issue by HauHe** [KTH-dESA/OSeMOSYS_step#36]
When passing the installed capacity from one step to the next OSeMOSYS might crash if the installed capacity passed is slightly higher than implemented limits due to the tolerance of solvers.

**Comment by HauHe** [comment]
Hi @trevorb1, I'm not sure if we discussed this issue.
I had fixed it in the code before you started working, but I think I didn't mention it to you and in your code I couldn't find if you consider this. 
The issue is that solvers have a bit of a tolerance, i.e., if I have for example a TotalAnnualCapacityLimit of 5 the solution might indicate 5.0000001.
I fixed this issue by rounding the `NewCapacity` to 4 digits.

**Comment by trevorb1** [comment]
@HauHe, did you want to check that the solution in PR #58 is what you had intended, please!
