### ISSUE TITLE
Line for results path in osemosys code can change

### ISSUE THREAD

**Issue by HauHe** [KTH-dESA/OSeMOSYS_step#37]
the main_step script changes the results path in the osemosys file when running models with GLPK. This creates an error when the lines in the OSeMOSYS file have changed.

**Comment by HauHe** [comment]
This is outdated as well if I'm not mistaken, right @trevorb1? 
In the new scripts you don't use the `ResultsPaths` in the OSeMOSYS code right?

**Comment by trevorb1** [comment]
Correct, @HauHe! We just copy over the model file to get around this if we are solving via GLPK. I think this is a more cumbersome solution, but more stable since we dont have to modify a specific line number in the model file each time.

**Comment by HauHe** [comment]
Perfect, thanks for the explanation had briefly looked at the code, but wasn't exactly sure how you solved, just got that you did it different, haha
